---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: tokyo
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "StartupWeekend Yokohama"
keywords:    "startupweekendyokohama, startupweekend, startup, yokohama, weekend"
description: "金曜夜から日曜夜まで54時間かけて開催されるスタートアップイベント"
#source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
image: "img/swy_navy.png"
google_analytics_key: UA-61076592-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  navy:      '#1e50a2'
  gray:      '#dcdcdc'
